Creation of orders endpoints - gateway
PiotrRogulski/IO2-spec pull request #25
Opened 2022-05-21 18:39 UTC by SzyMan1337

Creating and changing gateway endpoints.

2022-05-21 19:02 UTC, PiotrRogulski requested changes

2022-05-21 19:02 UTC, PiotrRogulski commented on api-specification/GatewayMessages.raml
> +            description: Get courier status
Should be 'Set' or 'Update'

2022-05-22 07:47 UTC, SzyMan1337 commented on api-specification/GatewayMessages.raml
> +            description: Get courier status
Fixed :)

2022-05-22 09:58 UTC, PiotrRogulski approved these changes

2022-05-22 15:23 UTC, jszablanowski commented on api-specification/GatewayMessages.raml
> +            description: Get courier status
We should include this change in .html file

2022-05-22 15:39 UTC, merged